# Generated by Django 4.1.4 on 2023-01-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_wallet_amount_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='amount_currency',
            field=models.CharField(choices=[('RUB', 'рубли'), ('KZT', 'тенге'), ('USD', 'доллары')], default='KZT', max_length=3),
        ),
    ]
